server:
  port: 8082

spring:
  devtools:
    livereload:
      enabled: true
  r2dbc:
    url: r2dbc:mysql://localhost:3306/powerup_reactive_capacity
    username: root
    password:

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  sql:
    init:
      data-locations: classpath:/script.sql
      mode: embedded

appDescription: "Pragma Powerup"
appVersion: "1.0.0"
debug: false